### ISSUE TITLE
API Access

### ISSUE THREAD

**Issue by EliasPereirah** [google-deepmind/synthid-text#1]
Please provide API access for SynthID.
Ease of implementation: Providing access via API facilitates the integration of the technology into various systems and platforms, making it accessible to a wider audience.

**Comment by RyanMullins** [comment]
Hi @EliasPereirah! 

This repo is a static reference implementation of SynthID Text to enable reproducibility of the [research paper](https://www.nature.com/articles/s41586-024-08025-4) published in _Nature_ by the community. It is not meant for production use or consumption via APIs. 

For production use with open weights models, please look at the APIs available in Hugging Face Transformers staring in v4.46.0. See our [blog post](https://huggingface.co/blog/synthid-text) and [Space](https://huggingface.co/spaces/google/synthid-text) for more on how to use this implementation.

For production use Google's proprietary models, please look at [Google Cloud's offerings](https://cloud.google.com/blog/products/ai-machine-learning/vertex-ai-next-2023-announcements), which also support multi-modal outputs such as [images](https://cloud.google.com/blog/products/ai-machine-learning/a-developers-guide-to-imagen-3-on-vertex-ai).
