### ISSUE TITLE
The model device in the default settings may not be as expected.

### ISSUE THREAD

**Issue by LOVEANDNINENINE** [google-deepmind/synthid-text#14]
This is just a very minor issue. I personally think your code is very well-structured. However, it seems that multi-GPU machines were not considered (even though I’m only using one GPU). In Colab, the model is loaded with the 'auto' mode for device_map, but when the global DEVICE is set, it is configured as 'cuda:0'. It would be more user-friendly to assign the device_map to the global variable DEVICE for better accessibility, especially for beginners.

**Comment by RyanMullins** [comment]
Thanks for the feedback, @LOVEANDNINENINE. 

You're correct that supporting multi-accelerator configurations is not a design goal for this codebase, which is focused on reproducibility of the associated [research paper](https://doi.org/10.1038/s41586-024-08025-4). Instead, we assume that users will be limited to whatever is [supported by Colab](https://research.google.com/colaboratory/faq.html#gpu-availability), which today is a single GPU per runtime. 

Given this assumption, setting `device_map="auto"` will [infer](https://huggingface.co/docs/accelerate/v1.1.0/en/package_reference/utilities#accelerate.infer_auto_device_map) the correct device map and [fill the available accelerator](https://huggingface.co/docs/accelerate/en/concept_guides/big_model_inference#designing-a-device-map) (i.e., `cuda:0`). We find to be sufficiently user-friendly for our goals, and definitely more maintainable than [defining custom `device_map`s](https://huggingface.co/docs/accelerate/v1.1.0/en/package_reference/big_modeling#accelerate.load_checkpoint_and_dispatch.device_map) using the [`torch.device` identifier](https://pytorch.org/docs/stable/tensor_attributes.html#torch-device) from `DEVICE` for each model/accelerator configuration. If users find that their model is not fitting on the accelerators available to them, they will need to consider [purchasing a subscription](https://colab.research.google.com/signup).

We strongly encourage that users interested in multi-accelerator configurations first consider using the [production-grade SynthID Text implementation](https://huggingface.co/blog/synthid-text) available in Hugging Face Transformers. 

Researchers looking to directly reproduce _this work_ on multi-accelerator setups (e.g., [VMs](https://research.google.com/colaboratory/marketplace.html) or [enterprise resources](https://cloud.google.com/colab/docs/introduction)) will need to [fork this repo](https://github.com/google-deepmind/synthid-text/fork) and update the code accoridngly.
