### ISSUE TITLE
Discrepancies Between Published Techniques and Code Implementation

### ISSUE THREAD

**Issue by hifi-hyp** [google-deepmind/synthid-text#17]
It appears that the authors do not implement the tournament watermarking technique described in the paper in their actual code. Instead, the code seems to merely boost the probability of tokens with g=1.

**Comment by sdathath** [comment]
The tournament does boost the probability of tokens with g=1. Could you elaborate why you think the tournament isn't implemented? Could you point to the lines of code that you think implements a different algorithm?

**Comment by hifi-hyp** [comment]
> The tournament does boost the probability of tokens with g=1. Could you elaborate why you think the tournament isn't implemented? Could you point to the lines of code that you think implements a different algorithm?

```python
def update_scores(
    scores: torch.FloatTensor,
    g_values: torch.FloatTensor,
) -> torch.FloatTensor:
  """Updates scores using the g values.

  We assume that the scores are in the log space.
  Args:
    scores: Scores (batch_size, vocab_size).
    g_values: G values (batch_size, vocab_size, depth).

  Returns:
    Updated scores (batch_size, vocab_size).
  """
  _, _, depth = g_values.shape
  device = scores.device

  probs = torch.softmax(scores, dim=1)

  for i in range(depth):
    g_values_at_depth = g_values[:, :, i]
    g_mass_at_depth = (g_values_at_depth * probs).sum(axis=1, keepdims=True)
    probs = probs * (1 + g_values_at_depth - g_mass_at_depth)

  log_probs = torch.log(probs)
  log_probs = torch.where(
      torch.isfinite(log_probs), log_probs, torch.tensor(-1e12, device=device)
  )
  return log_probs
```

Thank you for your prompt response! Regarding the code for updating the scores, it seems to boost the probabilities of the winners across multiple rounds. However, based on the description in the paper, I understood that the final winner should be selected with a probability of 1, rather than relying on boosted probabilities. Could you kindly clarify if I might have misunderstood anything?

**Comment by sdathath** [comment]
The tokens for the first round of the tournament are sampled from the LLM distribution. Note that this set of tokens is not fixed with probability 1. 

Further, in case of ties within the tournament, the winner is chosen randomly between tied tokens. All of this to say that the winner is not selected with a probability of 1, but rather there is a distribution of winning tokens with different probabilities.

This distribution of winning tokens is what is computed in the code you shared. Please see Appendix E from the Supplementary Information section of the paper -- it shows how the distribution of winning tokens from the tournament is equivalent to the distribution computed in the code you shared.

**Comment by hifi-hyp** [comment]
> The tokens for the first round of the tournament are sampled from the LLM distribution. Note that this set of tokens is not fixed with probability 1.
> 
> Further, in case of ties within the tournament, the winner is chosen randomly between tied tokens. All of this to say that the winner is not selected with a probability of 1, but rather there is a distribution of winning tokens with different probabilities.
> 
> This distribution of winning tokens is what is computed in the code you shared. Please see Appendix E from the Supplementary Information section of the paper -- it shows how the distribution of winning tokens from the tournament is equivalent to the distribution computed in the code you shared.

Thank you! Appendix E has addressed all my concerns.
