### ISSUE TITLE
Project is not on PyPI

### ISSUE THREAD

**Issue by kwinkunks** [google-deepmind/synthid-text#3]
The README says:

> The core library is [distributed on PyPI](https://pypi.org/project/synthid-text/)

But the project is not there.

The Colab notebook suggests installing from there too; I used this instead:

    !pip install synthid-text@git+https://github.com/google-deepmind/synthid-text

**Comment by RyanMullins** [comment]
Thanks for pointing that out. Yesterday was a busy day for our small team. 

https://pypi.org/project/synthid-text/0.1.0/
